name: Changelog and Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    name: Generate Changelog and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate Changelog
        id: changelog
        run: |
          # Get the previous tag
          PREVIOUS_TAG=$(git tag --sort=-version:refname | grep -v "${{ github.ref_name }}" | head -1)
          echo "Previous tag: $PREVIOUS_TAG"
          echo "Current tag: ${{ github.ref_name }}"
          
          # Generate changelog between tags
          if [ -z "$PREVIOUS_TAG" ]; then
            # If no previous tag, get all commits
            CHANGELOG=$(git log --pretty=format:"- %s (%h)" --no-merges)
          else
            # Get commits between previous and current tag
            CHANGELOG=$(git log $PREVIOUS_TAG..${{ github.ref_name }} --pretty=format:"- %s (%h)" --no-merges)
          fi
          
          # Filter out chore, style, docs commits
          FILTERED_CHANGELOG=$(echo "$CHANGELOG" | grep -v -E "^- (chore|style|docs|ci):" || true)
          
          # Set output
          echo "changes<<EOF" >> $GITHUB_OUTPUT
          echo "$FILTERED_CHANGELOG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "previousTag=$PREVIOUS_TAG" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: |
            ## What's Changed

            ${{ steps.changelog.outputs.changes }}

            ## Installation

            ```bash
            npm install valkey-glidejs-mcp@latest
            ```

            ## MCP Configuration

            Add to your Claude Desktop config:
            ```json
            {
              "mcpServers": {
                "valkey-glide": {
                  "command": "npx",
                  "args": ["valkey-glidejs-mcp"]
                }
              }
            }
            ```

            **Full Changelog**: https://github.com/${{ github.repository }}/compare/${{ steps.changelog.outputs.previousTag }}...${{ github.ref_name }}
          token: ${{ github.token }}

      - name: Update CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: "docs: update CHANGELOG.md for ${{ github.ref_name }} [skip ci]"
          file_pattern: CHANGELOG.md
          create_branch: false
